### PR TITLE
Feature/detect dxvk

### PR DESCRIPTION
**Pull request by Nemirtingas**

### CODE REVIEW

**Comment by Nemirtingas** [comment]
Needs further testing but looks fine on DX9, DX10, DX11.

**Comment by Nemirtingas** [comment]
I'm surprised that dx9_app.exe worked because of the mutex in the dx9 present/presentex calling the swapchain present and locking again the same mutex throwing an exception.
To enable the logs, you need to clone spdlog in the `deps` directory and enable the cmake option `INGAMEOVERLAY_USE_SPDLOG`

**Comment by Nemirtingas** [comment]
image
Vulkan got hooked on my test

**Comment by Nemirtingas** [comment]
dxvk should not be put next to game files but in wine's system32 directory per the dxvk documentation.

**Comment by Nemirtingas** [comment]
On windows, you don't have any other choice but to put it next to the game files. You are not supposed to replace the files in system32 :), but on wine you should.

**Comment by Nemirtingas** [comment]
The screenshot is from ubuntu

**Comment by Nemirtingas** [comment]
This version should work on DX11, don't know about DX10

**Comment by Nemirtingas** [comment]
dxvk is still not officially 'supported', only detected. (DX12 lacks detection tho). It doesn't always work on Windows either.

**Comment by 0xD3ADCODE** [comment]
@Edremon how did you managed to get working overlay with gbe_fork? i've managed to build latest version of fork with this branch, but on steam deck there is still no overlay in DX11 games

**Comment by Nemirtingas** [comment]
Need a way to detect surface color order before merging it:
image

**Pull request merged**
